apiVersion: builtin
kind: ChartInflator
metadata:
  # The name here doesn't matter.
  name: kong
chartName: kong
releaseName: kong
values: values.yaml
releaseNamespace: kong
chartRepoUrl: https://charts.konghq.com
